{% set name = "asks" %}
{% set version = "2.4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 38de944eb350e7e4e3a918055fa8ff033da5f7b5ff385c1160a2d6b9d84783b0

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - async_generator
    - h11
    - anyio

test:
  imports:
    - asks
  requires:
    - curio
    - pytest
    - overly

about:
  home: https://github.com/theelous3/asks
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENCE.txt
  summary: asks is an async requests-like http lib, for use in conjunction with the wonderful curio and trio async libs.

extra:
  recipe-maintainers:
    - CJ-Wright
