travis:
  secure:
    BINSTAR_TOKEN: CFmf1vmkNOT1j4K39xWinsCFkpDZGHKY6V23se2L7n3p8QHDeP4gnyrpVA9dd0DZXM//4oVqDqcXhaQPkwBMvBKmy1tQ8o73ieQOpRxbl2PKR/oC2lGxtoCa6uNGIqB0e5570aUJtvupE2SiV3XKcQFE6oW0ggXhi2jseExmP5G6cH9sAao5L53pNq19qJ8RDPkj8x4O8/+i4jaBIXdDr0MqR4HmhAmVFRX1EN/+c0vaLO6OXi87Zl1s0gBrPaMcM2R7QK6gOfIgj0tsR/q/aIBgE78dWycaQrJPeN8U7Z2GiT+Q+vOU8vwbcevztJxOGmod3fnn5niQUWhsU9hKDXx4SezGIn0zX7usz/76cOBnjhfP+Tc9O4PyryFBUhV1YRIbcBpFlw1SIF9C8x3sEBgik/b5/wjKKX6FspTxgB6j+nAC9aCF4WX+ThY5zkELRcrqWvsVoXHOQz6AlO3uIYATkk7buzIbz2i2RS63xPz5xMYH5sHYF9EZk7gjZw4lzEK150LALHrD/41wFmtEMpy36qUES49KH0qneX41ftQeyCTdrGkqtVdDDQSIv6qEE7AV/5zdxijixjbwaGWU34LP+hEbDuEQEQ/3KR8zRlIe1lPcmAa29C6MkOkb/DrC2RXe5RclDfNRLCekS7xSPLAahaBZMK99QGh7F2DJ/pA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
